feature: страницы для избранных товаров, услуг, статей
veterinary-salons/frontend pull request #100
Opened 2023-09-03 11:26 UTC by Anton-Laid

2023-09-03 20:51 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/59ed418d-3619-403e-91c9-b0c8365226a4)

2023-09-03 20:59 UTC, AlinaLvova requested changes

2023-09-03 20:59 UTC, AlinaLvova commented on src/components/CardGood/index.jsx
> +  likes,
rename -> isLiked

2023-09-03 21:06 UTC, AlinaLvova requested changes

2023-09-03 21:06 UTC, AlinaLvova commented on src/assets/constants/constants.js
> +const dataSelectedProducts = [
Это скорее всего временная константа. Позже данные будем получать с сервера. Лучше сейчас создать отдельный файл, а после его удалить.

2023-09-04 09:54 UTC, Anton-Laid commented on src/assets/constants/constants.js
> +const dataSelectedProducts = [
В файле `constants.js` много временных переменных

2023-09-05 21:13 UTC, vivan1992 approved these changes

2023-09-05 21:15 UTC, AlinaLvova approved these changes

2023-09-05 21:16 UTC, merged