Feat/profile
veterinary-salons/frontend pull request #106
Opened 2023-09-03 19:29 UTC by vivan1992

Добавил редактирование профиля

2023-09-03 21:28 UTC, AlinaLvova commented
Начала ревьють. Надо дождаться вливания правок от Антона @Anton-Laid. И ответа дизайнеров. У них в фигме разные отступы. Ждем их ответа. 
@EkaterinaEgorovaDesigner 
уточните, пожалуйста, отступы

- [ ] error span. (там где input field)

- [ ] отступ от подзаголовка

- [ ] отступ от футера

![image](https://github.com/veterinary-salons/frontend/assets/37267494/bd755374-1b1f-417b-9a3f-282feb270007)
![image](https://github.com/veterinary-salons/frontend/assets/37267494/f42c66d5-dbba-4974-85f7-5eab27d228fd)
![image](https://github.com/veterinary-salons/frontend/assets/37267494/91f9820e-3779-4a99-87f6-f7593c200eeb)

После того, как получим ответ от дизайнеров. @Anton-Laid прошу тебя поправить сразу error span отступ и уже после его залить в рабочую ветку. @vivan1992 прими изменения эти и дальше твой реквест мерджим.

2023-09-03 21:37 UTC, AlinaLvova requested changes
Влить изменения из главной рабочей ветки

2023-09-04 06:05 UTC, Polina-KHV approved these changes

2023-09-04 07:41 UTC, Polina-KHV commented
Изменения от дизайнеров вносим hotfix правками по мере поступления

2023-09-04 07:42 UTC, AlinaLvova approved these changes

2023-09-04 07:42 UTC, merged

2023-09-04 07:44 UTC, vivan1992 commented
Верстка сделана по предыдущему варианту макета. После добавления расстояния между инпутами макет у дизайнеров весь поехал, поэтому и не сходится с мактом