Feature/authorization-page
veterinary-salons/frontend pull request #120
Opened 2023-09-06 20:15 UTC by Anton-Laid

- Сделана верстка.
- При входе на страницу на данный момент сохраняются данные в localStorage и header меняется 
- отредактировал ошибку с inputs. По умолчанию они были красного цвета

2023-09-07 15:30 UTC, AlinaLvova requested changes

2023-09-07 15:30 UTC, AlinaLvova commented on src/pages/Profile/index.jsx
> -  const handleClicExitProfile = () => {};
исправить на handleExitProfile

2023-09-07 15:30 UTC, AlinaLvova commented on src/components/EnterForm/index.jsx
>        ...values,
Думаю, компоненту лучше дать название SignInForm

2023-09-07 16:47 UTC, Polina-KHV commented on src/components/EnterForm/index.jsx
>        ...values,
done

2023-09-07 16:47 UTC, Polina-KHV commented on src/pages/Profile/index.jsx
> -  const handleClicExitProfile = () => {};
done

2023-09-07 19:23 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/b9dbc629-5691-4454-9f2e-2fae98208bdb)

2023-09-07 19:28 UTC, AlinaLvova commented on src/routes/root/index.jsx
> +const dataPathWithOnlyLogoHeader = ['/signin', '/recovery', '/signup'];
+ 404, no internet

2023-09-07 19:28 UTC, AlinaLvova commented on src/components/SignInForm/index.jsx
> +            onClick={() => {}}
почему удалила?

2023-09-07 19:34 UTC, Polina-KHV commented on src/routes/root/index.jsx
> +const dataPathWithOnlyLogoHeader = ['/signin', '/recovery', '/signup'];
ошибку делаю в другой ветке

2023-09-07 19:35 UTC, Polina-KHV commented on src/components/SignInForm/index.jsx
> +            onClick={() => {}}
пока роута нет такого, пусть стоит заглушка

2023-09-08 09:27 UTC, AlinaLvova approved these changes

2023-09-08 09:27 UTC, AlinaLvova commented on src/components/SignInForm/index.jsx
> +            onClick={() => {}}
ок

2023-09-08 09:27 UTC, AlinaLvova commented on src/routes/root/index.jsx
> +const dataPathWithOnlyLogoHeader = ['/signin', '/recovery', '/signup'];
Нужно будет тогда отдельной задачей сделать на страницах не лого, а header.

2023-09-08 09:27 UTC, merged