feature: GoodsCathegoryCardList for goods catalog
veterinary-salons/frontend pull request #121
Opened 2023-09-07 09:50 UTC by Polina-KHV

1. Сверстан компонент карточек с категориями товаров на странице каталога товаров

2023-09-07 18:53 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/9240129a-61e1-4d0f-96c7-498f2986ca65)

2023-09-07 18:53 UTC, AlinaLvova requested changes

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/index.jsx
> +          classes.card__img,
Семантика: Если выбор фильтра важен для содержания страницы и должен быть доступен для индексации поисковыми системами, использование <img> более семантично.
<img src="файл-картинки.jpg" alt="Выбор фильтра">
Посмотри на странице Main карточки услуг в пример.

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCardList/style.module.scss
> +  gap: 20px;
gap: 12px 20px;

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/style.module.scss
> +    gap: 12px;
gap: 4px;

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/style.module.scss
> +    letter-spacing: 1.2px;
letter-spacing: 1px;

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/style.module.scss
> +  &__img-feed-goodies {
при использовании тега 'img' от этих стилей можно отказаться

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/index.jsx
> +  img: PropTypes.string
В дальнейшем, если будешь использовать картинку через фоновое изображение, здесь лучше давать варианты для выбора.

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/index.jsx
> +const GoodsCathegoryCard = ({ link, title, img }) => (
Название отлично!

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCard/index.jsx
> +      <h3 className={classes.card__title}>{title}</h3>
тут скорее тег 'p'

Title 3 Bold 28 - это h3

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCardList/index.jsx
> +const GoodsCathegoryCardList = () => {
Именование отлично!

2023-09-07 18:53 UTC, AlinaLvova commented on src/components/GoodsCathegoryCardList/index.jsx
> +        img={item.value}
Вижу, что тут value и  селекторы названы одним именем.
Но лучше хранить в filterData.TypeForAll добавить ссылку на изображение:
 
options:{

    ....
    
    img: '../assets/..'
}

2023-09-08 09:38 UTC, Polina-KHV commented
Пока не вношу правки, жду ответ от дизайнеров насчет этих карточек.

2023-09-08 14:54 UTC, Polina-KHV commented
Внесла правки, @AlinaLvova посмотри

2023-09-09 09:31 UTC, AlinaLvova approved these changes
ок

2023-09-09 09:32 UTC, merged