Feat/page404
veterinary-salons/frontend pull request #125
Opened 2023-09-08 11:22 UTC by Polina-KHV

1. Компонент с сообщением об ошибке на странице ошибки ErrorPageMessage сделан единым с пропсами (раньше было 2 отдельных)
2. Создан общий файл ErrorBoundary для страниц ошибок
3. Добавлено отслеживание отсутствия сети на стороне пользователя, выводится соответствующая ошибка

2023-09-08 15:07 UTC, Polina-KHV commented
Установлена новая библиотека, нужно сделать npm ci

2023-09-08 17:22 UTC, AlinaLvova requested changes
Добавление отслеживания сети супер!

2023-09-08 17:22 UTC, AlinaLvova commented on src/components/ErrorPageMessage/index.jsx
> +function ErrorPageMessage({ width, title, msg, error404}) {
Лучше написать `message` для понимания

2023-09-08 17:22 UTC, AlinaLvova commented on src/components/ErrorPageMessage/index.jsx
> +      <h1 className={classes.error__title}>{title}</h1>
исправить на тег h2

2023-09-08 17:22 UTC, AlinaLvova commented on src/routes/index.jsx
> +          <ErrorBoundary errorType404={false} />
Я думаю, здесь можно опустить пропс (по умолчанию false)

2023-09-08 17:22 UTC, AlinaLvova commented on src/routes/ErrorBoundary/index.jsx
> +  errorType404: true,
Поставь лучше здесь по умолчанию false, чтобы не путаться. У тебя в компоненте ErrorPageMessage стоит false по умолчанию. Потому что при указании пропса не нужно будет указывать true или false, достаточно указать флаг (errorType404). См. пример с шапкой и лого, вот там отлично сделала :)

2023-09-09 09:11 UTC, AlinaLvova approved these changes
ok.

2023-09-09 09:11 UTC, merged