feature: создание карточки заказа
veterinary-salons/frontend pull request #133
Opened 2023-09-11 08:45 UTC by Anton-Laid

Была проблема с макетом. 
Есть общие компоненты в двух карточках, но по px они отличаются. 

![Снимок](https://github.com/veterinary-salons/frontend/assets/113182938/e77fe2c2-2fca-4418-a961-98122078109c)

![Снимок2](https://github.com/veterinary-salons/frontend/assets/113182938/36f99b66-43bc-4164-b338-14a5844335c5)

Пришлось давать несколько классов одним и тем жем комантанетам

2023-09-11 19:19 UTC, vivan1992 commented on src/components/OrderInformation/index.jsx
> +      )}
добавь общую обертку для элементов card__container

2023-09-11 19:21 UTC, AlinaLvova requested changes

2023-09-11 19:21 UTC, AlinaLvova commented on src/components/OrderInformation/index.jsx
> +      {delivery && (
через .map

2023-09-11 19:21 UTC, AlinaLvova commented on src/components/OrderInformation/index.jsx
> +  cost: '700',
сделай array и сгенерируй элементы в зависимости от данных в этом массиве

{
    title,
    value
}

2023-09-13 11:48 UTC, Anton-Laid commented
Исправил верстку и немного стили

2023-09-23 19:15 UTC, AlinaLvova approved these changes
ок!

2023-09-23 19:15 UTC, merged