Feature/creation advert price
veterinary-salons/frontend pull request #143
Opened 2023-09-21 09:18 UTC by Anton-Laid

Сверстана страница:

1280px
1440px
Прописана логика:

Все данные попадают в один объект

![Creation of advert price 1280](https://github.com/veterinary-salons/frontend/assets/113182938/3a208cf5-7995-4a0d-ab82-87ee3bf49cbf)

2023-09-23 19:21 UTC, AlinaLvova commented on src/assets/constants/DadaPrice.js
> +const datapPrice = [
dataServicePriceFilter

2023-09-23 19:56 UTC, AlinaLvova requested changes
Изменила верстку на дисплей флекс: теперь элементы идут друг за другом с расстоянием gap=20px. Проверила по PP.
Изменила начальное значение на пустое. Если стоит ноль, то при установке курсора в зависимости от его позиции (до нуля или после) будет вводится неверное число. Например, 0 курсор до => 50

2023-09-23 19:56 UTC, AlinaLvova commented on src/components/AdCreation/AdPrice/index.jsx
> +      <InputPrice getInput={setForm} name={name} />
почему тут нет префикса 'от' или он по умолчанию?

2023-09-23 19:56 UTC, AlinaLvova commented on src/ui/forms/inputs/inputPrice/index.jsx
>    );
при вводе числа и переходу ввода нового числа в другой клетке, предыдущая становится цвета "неактивного". Поправь, пожалуйста, чтобы после ввода всех в конечном итоге они все были черным, а не серым цветом.

2023-09-23 19:56 UTC, AlinaLvova commented on src/assets/constants/DadaPrice.js
> +export default datapPrice;
посмотри внимательно на название файла. DadaPrice.js 
Лучше добавить эти данные в уже созданный файл, там где лежат похожие массивы.

2023-09-23 19:56 UTC, AlinaLvova commented on src/pages/CreationAdvertPrice/index.jsx
> +const CreationPriceCervices = ({ getPrice }) => {
название отличное :)

2023-09-23 19:56 UTC, AlinaLvova commented on src/pages/CreationAdvertPrice/index.jsx
> +      <h2 className={classes.price__title}>Стоимость услуг(и)</h2>
тег h3

2023-09-23 19:56 UTC, AlinaLvova commented on src/pages/CreationAdvertPrice/index.jsx
> +          />
отлично массивом!

2023-09-28 08:40 UTC, Anton-Laid commented on src/components/AdCreation/AdPrice/index.jsx
> +      <InputPrice getInput={setForm} name={name} />
Да, я поставил его по умолчанию

2023-09-28 08:50 UTC, Anton-Laid commented
Все исправил

2023-10-04 11:56 UTC, AlinaLvova approved these changes
Добавила TODO для валидации полей. Можно сделать сейчас, если не займет много времени, можно оставить на потом.
Оставила вопрос для @Anton-Laid и @vivan1992

2023-10-04 11:56 UTC, AlinaLvova commented on src/pages/CreationAdvertPrice/index.jsx
> +  getPrice: PropTypes.func,
@Anton-Laid, за что отвечает функция getPrice?

2023-10-04 11:56 UTC, AlinaLvova commented on src/routes/index.jsx
>        <Route path="advert-success" element={<AdvertSuccess />} />
Возможно тут должна быть одна страница, связанная с этими переходами. Что думаешь, @vivan1992?

2023-10-05 19:00 UTC, merged