Feat/signup
veterinary-salons/frontend pull request #146
Opened 2023-09-21 18:09 UTC by Polina-KHV

1. Созданы страницы регистрации, авторизации и восстановления пароля
2. Данные пользователя пока не сохраняются в локал сторадже, буду это подключать вместе с бэком. Пока хардкод)
3. Валидация ошибок, приходящих с бэка также будет доделана позже.
4. Данные аккаунта (для компонента MailAccount) после выхода из учетки будут храниться в локал сторадже. Пока что это просто ключ onAccount.

2023-09-21 19:17 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/8eabe223-f276-41c8-a5d3-8f06c304b1f8)
я бы сделала max-content в max-width, потому что сильно влево уезжает. режет глаз немного :)

2023-09-21 19:24 UTC, AlinaLvova requested changes
Проверить места, где остались вывод консоль логов

2023-09-21 19:24 UTC, AlinaLvova commented on src/components/Filters/GoodsFilter/index.jsx
> +      console.log(values)
оставить или убрать?

2023-09-21 19:24 UTC, AlinaLvova commented on src/components/RecoveryFormCode/index.jsx
> +  console.log(isOnAccount);
оставить или пока нужно?

2023-09-21 19:24 UTC, AlinaLvova commented on src/components/RecoveryFormCode/index.jsx
> +  console.log(isActive);
оставить или нужно?

2023-09-21 19:24 UTC, AlinaLvova commented on src/components/SignInAccountForm/index.jsx
> +      <h2 className={classes.form__title}>Войдите в аккаунт</h2>
h3

2023-09-21 19:24 UTC, AlinaLvova commented on src/components/SignInAccountMain/index.jsx
> +        <h3 className={classes.auth__subtitle}>Вы вышли из аккаунта:</h3>
это тег p

2023-09-21 19:24 UTC, AlinaLvova commented on src/components/SignInAccountMain/index.jsx
> +      <h2 className={classes.auth__title}>Войдите в аккаунт</h2>
это тег h3

2023-09-21 19:25 UTC, Polina-KHV commented on src/components/Filters/GoodsFilter/index.jsx
> +      console.log(values)
Пока оставляем

2023-09-21 19:25 UTC, Polina-KHV commented on src/components/RecoveryFormCode/index.jsx
> +  console.log(isOnAccount);
Пока оставляем

2023-09-21 19:25 UTC, Polina-KHV commented on src/components/RecoveryFormCode/index.jsx
> +  console.log(isActive);
Пока оставляем

2023-09-23 10:48 UTC, vivan1992 reviewed
не выдает ошибку при восстановлении пароля, если пароли разные

2023-09-23 10:48 UTC, vivan1992 commented on src/components/RecoveryFormCode/index.jsx
> +  // TODO: Доработать функциональность валидации кода (добавить isActive в кнопку сабмита)
не исправила это замечание

2023-09-23 13:49 UTC, Polina-KHV commented on src/components/RecoveryFormCode/index.jsx
> +  // TODO: Доработать функциональность валидации кода (добавить isActive в кнопку сабмита)
Не поняла, про какое ты замечание. Если про коммент TODO, то это я его и написала. Доработаю когда будем уже подключать бэк

2023-09-23 13:52 UTC, Polina-KHV commented
@vivan1992 в макете нет варианта с ошибкой. Я сделала просто так, что если пароли не совпадают, форма не становится валидной и не возможно отправить данные (так было проще, если честно). Думаешь нужно перенести сравнение паролей на сабмит?

2023-09-23 16:56 UTC, vivan1992 commented
@Polina-KHV если пока это сложно то можно так оставить, просто непонятно из за чего кнопка не валидна если нет текста ошибки

2023-09-23 16:56 UTC, vivan1992 commented
конфликты только исправь тогда и можно вливать

2023-09-23 17:19 UTC, Polina-KHV commented
@vivan1992 можно на каком-нибудь созвоне со всеми посмотреть, как лучше будет. Ошибки все равно с подключением бэка буду доделывать.
Согласуй реквест плиз)

2023-09-23 19:03 UTC, AlinaLvova approved these changes
ok!

2023-09-23 19:04 UTC, merged