Feature/ad-creation
veterinary-salons/frontend pull request #147
Opened 2023-09-21 19:26 UTC by MariaTsay

Верстка шагов по созданию объявления специалиста (без рефакторинга):
1. Создала общую форму adForm
2. 1 шаг adType
3. 2 шаг adTitle
4. 3 шаг пока только adDogHandler - тк остальные страницы по услугам специалистов идентичные, то сначала решила показать один вид.
5. https://github.com/veterinary-salons/frontend/issues/138
6. Универсальную форму со списком чек-боксов пока не сделала, работаю в другой ветке с ней и пока не особо получается

2023-09-24 17:45 UTC, AlinaLvova reviewed
Единственное это пока не понятно как будет осуществляться переход (step two, step three и т.д.) 
Остальное хорошо!

2023-09-24 17:45 UTC, AlinaLvova commented on src/assets/constants/adCreationData.js
> +    },
1. Отформотировать файл (пробелы, лишние строки пустые)

2023-09-24 17:45 UTC, AlinaLvova commented on src/assets/constants/adCreationData.js
> +const adTypeOptions = [
2. Эти данные убрать в файл константы. Этот файл удалить.

2023-09-25 17:53 UTC, MariaTsay commented
> Единственное это пока не понятно как будет осуществляться переход (step two, step three и т.д.) Остальное хорошо!

да, по функционалу не очень понимаю, как это делать, потребуется чья-нибудь помощь

2023-10-04 21:05 UTC, AlinaLvova requested changes
@vivan1992 помоги здесь с настройкой роутов

2023-10-04 21:05 UTC, AlinaLvova commented on src/assets/constants/adCreationData.js
> +    },
Еще раз, проверь все, отформатируй

2023-10-10 22:02 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/3705da08-aa06-449d-8ad4-2f816f7dc407)
решить проблему с валидацией полей. Ввела одинаковое название, при выборе - чекаются сразу оба.
Также когда добавляю должно сразу подчеркнуть активным выбранным чекбоксом. сейчас же просто добавляется.

2023-10-10 22:03 UTC, AlinaLvova commented
должно быть так
![image](https://github.com/veterinary-salons/frontend/assets/37267494/1a10b3a3-313e-4053-8a4e-af87ad3ab3fd)
сейчас так
![image](https://github.com/veterinary-salons/frontend/assets/37267494/193d6a80-b53d-4400-8e94-f66b4e57192b)

2023-10-10 22:06 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/78057dac-7409-4685-ad2d-8ece73b957af)
Решить проблему с валидацией. Плохо, что первое число больше второго.

2023-10-10 22:08 UTC, AlinaLvova commented
Не заметила ранее, что эти компоненты переиспользуемые. 
![image](https://github.com/veterinary-salons/frontend/assets/37267494/d566096f-e70f-48bd-98d1-e1d757377cf5)

Они у меня в другой ветке уже сверстаны. Добавлю сначала свою ветку, потом решу конфликт с этой. Использую свои компоненты.

2023-10-10 22:10 UTC, AlinaLvova commented
![image](https://github.com/veterinary-salons/frontend/assets/37267494/feadbaef-f62c-43dc-a4e7-d76cd1e0b981)

кнопка "далее" не должна быть активной при пустом значении

2023-10-10 22:12 UTC, AlinaLvova commented
как здесь не активна. тут все ок!
![image](https://github.com/veterinary-salons/frontend/assets/37267494/da481586-d441-42c2-a3d9-af3d6d5186be)

2023-10-10 22:13 UTC, AlinaLvova requested changes
Поправить по мелочи. Доработать некоторые моменты - очень важно перед связыванием с беком.
Напишите, как будут храниться данные и собираться? через redux?

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +const ServiceChanges = ({ variant }) => {
лучше переименовать в EditProfileServices

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +  const version = (name) => {
const versionData = {
  zoonyanya: dataTasks,
  cynologist: dataFormatWork,
  groomer: dataGrooming,
  veterinarian: dataTasks,
};

const version = (name) => versionData[name] || '';

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +  console.log(datas);
удалить лишние консоль логи

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +          <h3 className={classes['service-changes__block-name']}>
Здесь при изменении дропдауна на новый тип специлиста, моментально должны отобразиться новые фильтры для конкретного специлиста. Используй зависимости. 
В заголовке пока можно не менять, пока не нажать на кнопку "сохранить данные"

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +          <AdPrice
Здесь в графе "Укажите стоимость услуг(и)" также для каждого типа специалиста сейчас по умолчанию в макете есть заданные услуги и приблизтельная начальная стоимость. Эти данные должны менять также как и чекбоксы выше.

Пример для кинолога:
Коррекция проблемного поведения
от 3 000 ₽ 
до 5 000 ₽ 

Обучение командам
от 500 ₽ 
до 1 500 ₽

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +    'zoonyanya',
pet-sitter :)

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/ServiceChanges/index.jsx
> +    'veterinarian',
уже приняли писать "vet" в коде

2023-10-10 22:13 UTC, AlinaLvova commented on src/assets/constants/constants.js
> +  variantVeterinarians: [
почему тут написано в названии вариантВетеринары? Смысл не понятен - поясните.

2023-10-10 22:13 UTC, AlinaLvova commented on src/assets/constants/getRoutes.js
> +const routeNext = (path, step) => {
может быть в названии отобразить, что это именно для объявления next?

2023-10-10 22:13 UTC, AlinaLvova commented on src/assets/constants/getRoutes.js
> +const routeNext = (path, step) => {
или в названии самого файла только

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/AdDogHandler/AdDogHandlerStepTwo/index.jsx
> +  console.log(values);
консоль!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/AdDogHandler/index.jsx
> +  console.log(values);
консоль!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/AdForm/index.jsx
> +    <form className={classes.af}>
название класса исправить на ad-form

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/AdTitle/index.jsx
> +  console.log(info);
консоль!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/AdTitle/index.jsx
> +      <div className={classes['af__input-container']}>
исправить название af на ad-form

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/AdType/index.jsx
> +  console.log(veterinarInfo);
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adGroomer/AdGroomerStepTwo/index.jsx
> +  console.log(values);
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adGroomer/index.jsx
> +  console.log(values);
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adGroomer/AdGroomerStepTwo/index.jsx
> +      <div className={classes['af__checkbox-container']}>
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adPetSitter/index.jsx
> +  console.log(values);
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adPetSitter/index.jsx
> +      <div className={classes['af__checkbox-container']}>
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adVet/AdVetStepTwo/index.jsx
> +  console.log(values);
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdCreation/adVet/AdVetStepTwo/index.jsx
> +      <div className={classes['af__checkbox-container']}>
!

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/FillingSchedule/index.jsx
> +// import { arrAdSchedule } from '../../assets/constants/filters';
удалить все комментированные строки, которые не используются и не описывают какое-либо действие как комментарий

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdSchedule/index.jsx
> +  serviceTime: PropTypes.bool,
лучше назвать Duration of a Service

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/AdSchedule/index.jsx
> +  durationService: PropTypes.shape({}),
Set of Service Durations

2023-10-10 22:13 UTC, AlinaLvova commented on src/pages/FillingSchedule/index.jsx
> +const FillingSchedule = ({ getSchedule }) => {
старайся писать описание сверху, чтобы было понятно за что отвечает компонент

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/ChecboksList/index.jsx
> +            <input
при нажатии клавиши Enter должно срабатывать добавление нового инпута и создание нового пустого, а не переход по кнопке "далее"

2023-10-10 22:13 UTC, AlinaLvova commented on src/components/ChecboksList/index.jsx
> +            <input
Если не получится сделать, тогда пока оставим

2023-10-15 15:12 UTC, Polina-KHV approved these changes

2023-10-15 15:13 UTC, merged