Feat/profile
veterinary-salons/frontend pull request #157
Opened 2023-09-25 20:25 UTC by vivan1992

Добавлены страницы с услугами в профиль

2023-10-04 20:26 UTC, AlinaLvova commented
при переходе на вкладку Товары, нет изменений в хлебных крошках

![image](https://github.com/veterinary-salons/frontend/assets/37267494/decef309-ae73-4c66-84f2-48538abed452)
при переходе на вкладку Товары, нет изменений в хлебных крошках

2023-10-04 20:36 UTC, AlinaLvova commented
Это ок, если остается крошка, которая была уже? В данном примере "Услуги"

![image](https://github.com/veterinary-salons/frontend/assets/37267494/86c2054a-8ef4-4886-afa0-c7e473a660db)

2023-10-04 20:48 UTC, AlinaLvova requested changes
Мелкие замечания.
Разобраться, что творится в хлебных крошках.

2023-10-04 20:48 UTC, AlinaLvova commented on src/pages/ProfileServicesHistoryList/index.jsx
> +// и чтобы не создавать дополнительный файл констант а можно было потом просто тут удалить
Отлично!

2023-10-04 20:48 UTC, AlinaLvova commented on src/components/ServiceBookingCardList/index.jsx
> +        />
<ServiceBookingCard {...booking} />

2023-10-04 20:48 UTC, AlinaLvova commented on src/pages/BookingFeedback/index.jsx
> +const BookingFeedback = () => (
WorkInProgressPage или WorkInProgress

2023-10-04 20:48 UTC, AlinaLvova commented on src/components/BookingCancellation/index.jsx
>      console.log('Отменен');
console.log убрать, если нет необходимости

2023-10-04 21:46 UTC, AlinaLvova commented
Проблема с крошками решена. Надо влить изменения из ветки develop.

2023-10-06 18:08 UTC, vivan1992 commented on src/pages/BookingFeedback/index.jsx
> +const BookingFeedback = () => (
это страница отзыва и названа она как страница отзыва, просто пока тут заглушка

2023-10-09 21:17 UTC, AlinaLvova approved these changes

2023-10-09 21:18 UTC, merged