верстка карточки услуги для профиля
veterinary-salons/frontend pull request #164
Opened 2023-10-03 20:29 UTC by vivan1992

Сделана верстка карточки, пока без получаемых данных, т.к. непонятно в каком формате будут данные приходить в карточку, будет доделано после того как будут готовы страницы создания услуги

2023-10-04 20:54 UTC, AlinaLvova commented on src/modules/profileServiceCard/index.jsx
> +  const isAdd = false;
Может быть лучше убрать ветвление? Для карточки "добавления" лучше сделать отдельный компонент. Или сделать общий для фона (фиолетовая карточка) и унаследовать этого родителя потомками с карточкой "добавления" (с кнопкой плюс) и карточкой "информации".

2023-10-04 20:56 UTC, AlinaLvova commented on src/modules/profileServiceCard/index.jsx
> +  const isAdd = false;
Может быть лучше убрать ветвление? Для карточки "добавления" лучше сделать отдельный компонент. Или сделать общий для фона (фиолетовая карточка) и унаследовать этого родителя потомками с карточкой "добавления" (с кнопкой плюс) и карточкой "информации".

2023-10-04 20:57 UTC, AlinaLvova requested changes
@vivan1992 напиши, что думаешь по поводу отдельного компонента?

2023-10-06 18:04 UTC, vivan1992 commented on src/modules/profileServiceCard/index.jsx
> +  const isAdd = false;
Хорошо сделаю разными компонентами

2023-10-09 21:09 UTC, AlinaLvova approved these changes

2023-10-09 21:09 UTC, merged