hotfix: adapt goods1280 styles
veterinary-salons/frontend pull request #166
Opened 2023-10-04 19:59 UTC by MariaTsay

1. Сделана верстка каталога с товарами на 1280
2. Поправила картинку ветаптеки
3. https://github.com/veterinary-salons/frontend/issues/165

2023-10-04 21:15 UTC, AlinaLvova commented
Здесь ожидалось следующее:
Растягивание (резиновая верстка). Под хлебными крошками всегда идет строго название заголовка. Четко под ним.
Дальше компонент заполняет всю ширину родителя (выделено синим) и полностью растягивает свои компоненты на 100% ширины.

![image](https://github.com/veterinary-salons/frontend/assets/37267494/cf5508ad-287b-40b3-8484-a7aef83e48bd)

Подсказка: смотри на хлебные крошки. Они ориентир. 

![image](https://github.com/veterinary-salons/frontend/assets/37267494/1d50fe23-f579-476a-adcc-336ef4d9229f)

2023-10-04 21:15 UTC, AlinaLvova requested changes
Переделать :) комментарий выше

2023-10-05 17:06 UTC, Polina-KHV commented
@MariaTsay 
В руте настроила ширину колонки контента, так что для sections на разных страницах можно ставить просто width: 100%.
Марджины по бокам будут сами автоматически разъезжаться.

Здесь этого не видно, можешь подтянуть себе ветку feat/articles.

![image](https://github.com/veterinary-salons/frontend/assets/113764110/28b6be62-3212-46e1-906b-5239004412fc)

2023-10-05 18:35 UTC, AlinaLvova approved these changes

2023-10-05 18:35 UTC, merged